apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jsuy0vnh3-nodejs 
  janus-idp.io/tekton: jsuy0vnh3-nodejs
  backstage.io/kubernetes-id: jsuy0vnh3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jsuy0vnh3-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml