apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jsuy0vnh3-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-65598a079d.ud87.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:b95377127439f52ff6c4adedcedd1fdbb2eb4da5@sha256:48a9ac89fcbaf6a841aad493bea5ccbdc7e98babeb4a7c22152f6f225baf76aa
          name: container-image
